# Generated by Django 3.2.5 on 2021-07-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvmlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_test',
            new_name='question_text',
        ),
    ]
